# version: "3.8"

services:
  videoshare-api1:
    build: .
    container_name: videoshare-api1
    networks:
      - app-network
    restart: always
    environment:
      - PORT=5001
    env_file:
      - ./.env
    volumes:
      - ./public:/app/public

  videoshare-api2:
    build: .
    container_name: videoshare-api2
    networks:
      - app-network
    restart: always
    environment:
      - PORT=5002
    env_file:
      - ./.env
    volumes:
      - ./public:/app/public

  videoshare-api3:
    build: .
    container_name: videoshare-api3
    networks:
      - app-network
    restart: always
    environment:
      - PORT=5003
    env_file:
      - ./.env
    volumes:
      - ./public:/app/public

  nginx:
    build: ./nginx
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www:/var/www
    depends_on:
      - videoshare-api1
      - videoshare-api2
      - videoshare-api3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
