name: videoshare

services:
  videoshare-api1:
    build: .
    container_name: videoshare-api1
    networks:
      - app-network
    restart: always
    environment:
      - PORT=5001
    env_file:
      - ./.env
    volumes:
      - ./public:/app/public

  # videoshare-api2:
  #   build: .
  #   container_name: videoshare-api2
  #   networks:
  #     - app-network
  #   restart: always
  #   environment:
  #     - PORT=5002
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./public:/app/public

  # videoshare-api3:
  #   build: .
  #   container_name: videoshare-api3
  #   networks:
  #     - app-network
  #   restart: always
  #   environment:
  #     - PORT=5003
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./public:/app/public

  nginx:
    build: ./nginx
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites.conf.template:/etc/nginx/templates/default.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www:/var/www
    depends_on:
      - videoshare-api1
      # - videoshare-api2
      # - videoshare-api3
    networks:
      - app-network
      - edge

networks:
  app-network:
    driver: bridge
  edge:
    name: ${SHARED_PROXY_NETWORK:-shared-proxy}
    external: true
